from dataclasses import replace
from datetime import UTC, datetime
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from blindspot import __version__
from blindspot.actions import RecommendationContext, RecommendationEngine
from blindspot.codeowners import (
    CodeOwnersValidator,
    find_codeowners_file,
    parse_codeowners,
)
from blindspot.collector import GitCollector, is_bot_author
from blindspot.collector.bitbucket import (
    BitbucketAuthError,
    BitbucketClient,
    BitbucketError,
    BitbucketPRCollector,
    detect_bitbucket_remote,
    load_bitbucket_config,
)
from blindspot.collector.filters import FileFilter
from blindspot.collector.github import (
    PRCollector,
    detect_github_remote,
    is_gh_authenticated,
    is_gh_available,
    load_github_config,
    make_github_client,
)
from blindspot.dependency_graph import (
    DependencyGraphBuilder,
    ImportanceEngine,
    ModuleGraph,
    aggregate_modules,
)
from blindspot.dependency_graph import (
    top_n as central_top_n,
)
from blindspot.dependency_graph.builder import auto_detect_code_root
from blindspot.risk_models.bus_factor import top_level_dir
from blindspot.diff_analysis import DiffChurnSummary, classify_file, summarise
from blindspot.narrative import (
    NarrativeConfigError,
    NarrativeEngine,
    generate_narrative,
    load_narrative_config,
)
from blindspot.narrative.client import MissingAPIKey, NarrativeError, build_client
from blindspot.ownership import OwnershipEngine
from blindspot.report import (
    DepartureContext,
    ReportContext,
    ReportRenderer,
    compute_remaining_gaps,
)
from blindspot.resilience import ResilienceScoreEngine
from blindspot.resilience.profile import detect_profile
from blindspot.review_graph import ReviewGraph, ReviewGraphBuilder
from blindspot.risk_models import (
    AIReadinessEngine,
    BusFactorEngine,
    CorrectionLoadEngine,
    DepartureSimulation,
    KnowledgeDecayEngine,
)
from blindspot.risk_models.departure import DepartureReport
from blindspot.trend import TrendEngine

app = typer.Typer(
    name="blindspot",
    help="Knowledge Factor — the bus factor for the AI era.",
    no_args_is_help=True,
)
console = Console()


def _resolve_service_prefix(repo_path: Path, code_root: str) -> str:
    """Resolve the effective directory prefix to strip before deciding a
    file's service.

    When ``code_root`` looks like a source root that contains exactly one
    Python-package-style directory (e.g. ``src/`` contains only
    ``blindspot/``), the package directory is appended to the prefix so a
    single-package layout doesn't collapse into one giant service. With
    multiple packages under the source root, the prefix stays at the root.
    """
    if not code_root or code_root == ".":
        return ""
    base = repo_path / code_root
    try:
        children = [
            p for p in base.iterdir()
            if p.is_dir() and not p.name.startswith((".", "_"))
            and p.name not in {"tests", "test", "__pycache__"}
        ]
    except (OSError, FileNotFoundError):
        return code_root.rstrip("/")
    if len(children) == 1:
        return f"{code_root.rstrip('/')}/{children[0].name}"
    return code_root.rstrip("/")


def _build_service_of(prefix: str):
    """Return a ``service_of(path) -> service`` function aware of a prefix.

    When ``prefix`` is empty, falls back to ``top_level_dir`` (path's first
    segment). When a prefix is provided (e.g. ``"src/blindspot"``), paths
    under it are stripped first so the *service* is the first directory
    **inside** that prefix. This stops a Python package collapsing into a
    single "src" or "blindspot" pseudo-service.
    """
    if not prefix:
        return top_level_dir
    p = prefix.rstrip("/") + "/"

    def service_of(path: str) -> str:
        if path.startswith(p):
            return top_level_dir(path[len(p):])
        return top_level_dir(path)

    return service_of


def _is_alertable(path: str, file_filter: FileFilter) -> bool:
    """Same gate the recommendation rules use, for display tables.

    A path is alertable iff it's product code (not test/docs/chore) AND
    not classified as generated by the file filter. Keeps display
    consistent with recommendation output.
    """
    if file_filter.is_generated(path):
        return False
    return classify_file(path) == "code"


def _passes_importance(
    path: str, importance_map: dict[str, float], threshold: float
) -> bool:
    """Mirror of RecommendationEngine._passes_importance for display tables.

    Empty map → no filtering (graph disabled / no imports). Otherwise keep
    only files whose PageRank importance meets the threshold. Files absent
    from the graph (e.g. unsupported language) are treated as below
    threshold and dropped from display, matching recommendation behavior.
    """
    if not importance_map:
        return True
    return importance_map.get(path, 0.0) >= threshold


@app.command()
def scan(
    path: Path = typer.Argument(Path("."), help="Repository path to scan."),
    output: Path = typer.Option(
        Path("blindspot_report.html"), "--output", "-o", help="HTML report output path."
    ),
    since_days: int = typer.Option(180, "--since-days", help="Analysis window in days."),
    include_merges: bool = typer.Option(False, "--include-merges"),
    with_reviews: bool = typer.Option(
        True,
        "--with-reviews/--no-reviews",
        help="Auto-fetch PR/review data when credentials are available "
        "(GitHub: token or gh CLI; Bitbucket: app password). On by "
        "default — if no credentials are detected, the scan continues "
        "silently and the report shows how to enable it. "
        "Use --no-reviews to skip entirely.",
    ),
    max_prs: int = typer.Option(
        50, "--max-prs", help="Maximum PRs to fetch when --with-reviews is set."
    ),
    github_token: str = typer.Option(
        "", "--github-token",
        help="GitHub personal access token (overrides .blindspot.yaml). "
        "Needed for private repos when the gh CLI isn't available. "
        "Never read from environment variables.",
    ),
    bitbucket_username: str = typer.Option(
        "", "--bitbucket-username",
        help="Bitbucket Cloud username (overrides .blindspot.yaml). "
        "Never read from environment variables.",
    ),
    bitbucket_app_password: str = typer.Option(
        "", "--bitbucket-app-password",
        help="Bitbucket Cloud app password with pullrequest:read + "
        "repository:read scopes (overrides .blindspot.yaml).",
    ),
    check_codeowners: bool = typer.Option(
        True,
        "--check-codeowners/--no-check-codeowners",
        help="Validate CODEOWNERS file (if present) against actual ownership.",
    ),
    no_dependency_graph: bool = typer.Option(
        False, "--no-dependency-graph",
        help="Skip building the file-dependency graph (faster, but recommendations "
        "won't be filtered by structural importance).",
    ),
    code_root: str = typer.Option(
        "", "--code-root",
        help="Repo-relative directory to constrain the dependency graph to. "
        "Default: auto-detect (prefers src/, then lib/, then app/, otherwise repo root). "
        "Set to '.' to scan the whole repo.",
    ),
    include_tests_in_graph: bool = typer.Option(
        False, "--include-tests-in-graph",
        help="Include files under tests/, examples/, docs/ in the dependency "
        "graph. Off by default — those folders pollute the architectural view. "
        "They still count for ownership and decay regardless of this flag.",
    ),
    importance_threshold: float = typer.Option(
        0.005, "--importance-threshold",
        help="PageRank threshold below which files are excluded from recommendations.",
    ),
    simulate_top_departures: int = typer.Option(
        3, "--simulate-top-departures",
        help="Add 'what-if' departure scenarios to the report for the top-N "
        "contributors by aggregate ownership coverage. Set to 0 to disable.",
    ),
    simulate_departures: str = typer.Option(
        "", "--simulate-departures",
        help="Add a single multi-person 'what-if' departure scenario to the "
        "report. Comma-separated emails. Example: "
        '--simulate-departures "alice@x.com,bob@x.com,carol@x.com" — '
        "renders one combined card on top of the top-N scenarios.",
    ),
    include_bots: bool = typer.Option(
        False, "--include-bots",
        help="Include automated authors (release-bots, dependabot, "
        "github-actions, etc.) in ownership and recommendations. "
        "Off by default — automated commits inflate apparent contribution "
        "and produce nonsense advice like 'pair Release Bot on CHANGELOG'.",
    ),
    narrative_lang: str = typer.Option(
        "en",
        "--narrative-lang",
        help="Language for the LLM narrative: 'en' or 'tr'.",
    ),
    api_key: str = typer.Option(
        "", "--api-key", help="LLM API key (overrides .blindspot.yaml).",
    ),
    model: str = typer.Option(
        "", "--model", help="LLM model id (overrides config).",
    ),
    provider: str = typer.Option(
        "", "--provider", help="LLM provider (default: anthropic).",
    ),
) -> None:
    """Scan a repository and generate a knowledge risk report."""
    collector = GitCollector(path, since_days=since_days, include_merges=include_merges)
    commits = list(collector.collect())

    if not include_bots:
        before = len(commits)
        commits = [
            c for c in commits
            if not is_bot_author(c.author_email, c.author_name)
        ]
        filtered = before - len(commits)
        if filtered:
            console.print(
                f"  Filtered {filtered} commit{'s' if filtered != 1 else ''} "
                f"from automated authors (use --include-bots to keep them)."
            )

    authors = {c.author_email for c in commits}
    files: set[str] = set()
    total_additions = 0
    total_deletions = 0
    for c in commits:
        for f in c.files:
            files.add(f.path)
            total_additions += f.additions
            total_deletions += f.deletions

    summary = Table(title=f"blindspot scan — {path}")
    summary.add_column("Metric")
    summary.add_column("Value", justify="right")
    summary.add_row("Window (days)", str(since_days))
    summary.add_row("Commits", str(len(commits)))
    summary.add_row("Unique authors", str(len(authors)))
    summary.add_row("Files touched", str(len(files)))
    summary.add_row("Lines added", str(total_additions))
    summary.add_row("Lines deleted", str(total_deletions))
    console.print(summary)

    review_graph: ReviewGraph | None = None
    diff_summary: DiffChurnSummary | None = None
    prs: list = []
    pr_count = 0
    pr_truncated = False
    reviews_enabled = False
    detected_remote: str | None = None

    if with_reviews:
        # Auto-mode: detect a recognised remote, try credentials silently.
        # When no credentials are available, the scan continues and the
        # report shows a contextual hint on how to enable review metrics.
        gh_remote = detect_github_remote(path)
        bb_remote = detect_bitbucket_remote(path) if gh_remote is None else None

        if gh_remote is not None:
            detected_remote = "github"
            gh_config = load_github_config(
                repo_path=path,
                cli_token=github_token or None,
            )
            # Credentials check: explicit token OR gh CLI authenticated.
            has_creds = bool(gh_config.token) or (
                is_gh_available() and is_gh_authenticated()
            )
            if has_creds:
                client, backend = make_github_client(
                    prefer_gh=True,
                    token=gh_config.token or None,
                )
                limit_msg = {
                    "gh": "via [bold]gh[/bold] CLI (5000/hr)",
                    "token": "via token (5000/hr)",
                    "anonymous": "anonymous (60/hr — public repos only)",
                }[backend]
                console.print(
                    f"Fetching up to {max_prs} PRs for [bold]{gh_remote.slug}[/bold] "
                    f"— GitHub {limit_msg}…"
                )
                try:
                    pr_collector = PRCollector(
                        client, gh_remote.owner, gh_remote.repo,
                        since_days=since_days, max_prs=max_prs,
                    )
                    prs, pr_truncated = pr_collector.collect()
                except Exception as e:
                    console.print(f"[red]GitHub error:[/red] {e}")
                    prs = []
            else:
                console.print(
                    "[dim]GitHub remote detected; review data skipped (no "
                    "credentials — see report for how to enable).[/dim]"
                )
        elif bb_remote is not None:
            detected_remote = "bitbucket"
            bb_config = load_bitbucket_config(
                repo_path=path,
                cli_username=bitbucket_username or None,
                cli_app_password=bitbucket_app_password or None,
            )
            if bb_config.is_complete:
                console.print(
                    f"Fetching up to {max_prs} PRs for "
                    f"[bold]{bb_remote.slug}[/bold] — Bitbucket Cloud…"
                )
                try:
                    bb_client = BitbucketClient(
                        username=bb_config.username,
                        app_password=bb_config.app_password,
                    )
                    bb_collector = BitbucketPRCollector(
                        bb_client, bb_remote.workspace, bb_remote.repo,
                        since_days=since_days, max_prs=max_prs,
                    )
                    prs, pr_truncated = bb_collector.collect()
                except BitbucketAuthError as e:
                    console.print(f"[red]Bitbucket auth error:[/red] {e}")
                    prs = []
                except BitbucketError as e:
                    console.print(f"[red]Bitbucket error:[/red] {e}")
                    prs = []
            else:
                console.print(
                    "[dim]Bitbucket remote detected; review data skipped "
                    "(no credentials — see report for how to enable).[/dim]"
                )

        pr_count = len(prs)
        if pr_count:
            review_graph = ReviewGraphBuilder().build(prs)
            diff_summary = summarise(prs)
            reviews_enabled = True
            msg = f"Fetched {pr_count} PRs"
            if pr_truncated:
                msg += " (truncated — partial data)"
            console.print(f"[green]✓[/green] {msg}")

    ownership = OwnershipEngine().compute(commits, review_graph=review_graph)

    codeowners_report = None
    if check_codeowners:
        co_path = find_codeowners_file(path)
        if co_path is not None:
            try:
                codeowners_file = parse_codeowners(co_path)
                codeowners_report = CodeOwnersValidator().validate(
                    codeowners_file, ownership, commits
                )
                console.print(
                    f"CODEOWNERS detected at [bold]{co_path.relative_to(path)}[/bold] "
                    f"({len(codeowners_file.rules)} rules) — validating against ownership…"
                )
            except Exception as e:
                console.print(f"[yellow]Could not parse CODEOWNERS: {e}[/yellow]")

    bus_factor = BusFactorEngine()
    decay_engine = KnowledgeDecayEngine()

    file_filter = FileFilter.from_repo(path)

    # Service definition: when a code root is detected (e.g. "src" or
    # "src/blindspot"), use the first directory *inside* it as the service
    # so a Python package isn't collapsed into one giant "src" service.
    resolved_code_root = (
        code_root.strip()
        if code_root.strip()
        else auto_detect_code_root(path)
    )
    service_prefix = _resolve_service_prefix(path, resolved_code_root)
    service_of = _build_service_of(service_prefix)
    if service_prefix:
        console.print(
            f"  Service root: [bold]{service_prefix}/[/bold] "
            f"(use --code-root to override)"
        )

    importance_map: dict[str, float] = {}
    top_central: tuple = ()
    top_central_models: tuple = ()
    module_graph: ModuleGraph | None = None
    if not no_dependency_graph:
        try:
            console.print("Building file dependency graph…")
            graph = DependencyGraphBuilder(
                file_filter=file_filter,
                code_root=resolved_code_root if resolved_code_root != "." else "",
                include_tests=include_tests_in_graph,
            ).build(path)
            importance_map = ImportanceEngine().compute(graph)
            module_graph = aggregate_modules(graph)
            if importance_map:
                # Enrich top-N with ownership info from the OwnershipMap.
                ranked = central_top_n(importance_map, graph, n=10)
                enriched = []
                for cf in ranked:
                    fos = ownership.for_file(cf.file)
                    top_email = fos[0].author_email if fos else None
                    top_cov = fos[0].coverage if fos else 0.0
                    enriched.append(
                        replace(cf, top_owner=top_email, top_owner_coverage=top_cov)
                    )
                top_central = tuple(enriched)
                tbl = Table(title=f"Top 10 central files ({graph.file_count} parsed, {graph.edge_count} edges)")
                tbl.add_column("File")
                tbl.add_column("Importance", justify="right")
                tbl.add_column("Dependents", justify="right")
                tbl.add_column("Top owner")
                for cf in top_central:
                    owner_label = (
                        ownership.label_for(cf.top_owner) if cf.top_owner else "—"
                    )
                    tbl.add_row(
                        cf.file,
                        f"{cf.importance * 100:.2f}%",
                        str(cf.in_degree),
                        owner_label,
                    )
                console.print(tbl)
            else:
                console.print(
                    "[dim]Dependency graph built but no importance scores "
                    "(repo may have no import statements in supported languages).[/dim]"
                )

            # AST-derived "central models": files defining many model classes
            # that other files actually depend on. Currently Python only.
            raw_models = graph.top_models(limit=10)
            if raw_models:
                enriched_models = []
                for m in raw_models:
                    fos = ownership.for_file(m.file)
                    top_email = fos[0].author_email if fos else None
                    top_cov = fos[0].coverage if fos else 0.0
                    enriched_models.append(
                        replace(m, top_owner=top_email, top_owner_coverage=top_cov)
                    )
                top_central_models = tuple(enriched_models)
                mtbl = Table(title=f"Top central models ({len(graph.model_files)} model-bearing files)")
                mtbl.add_column("File")
                mtbl.add_column("Model classes", justify="right")
                mtbl.add_column("Dependents", justify="right")
                mtbl.add_column("Top owner")
                for m in top_central_models:
                    mtbl.add_row(
                        m.file,
                        str(m.model_class_count),
                        str(m.dependents),
                        ownership.label_for(m.top_owner) if m.top_owner else "—",
                    )
                console.print(mtbl)
        except Exception as e:
            console.print(f"[yellow]Dependency graph skipped:[/yellow] {e}")

    services = bus_factor.for_services(ownership, service_of=service_of)
    file_bf = bus_factor.for_files(ownership)
    critical_files = [
        f for f in file_bf
        if f.risk_level == "critical"
        and _is_alertable(f.file, file_filter)
        and _passes_importance(f.file, importance_map, importance_threshold)
    ]
    decays_all = decay_engine.for_files(commits, ownership)
    decays = [
        d for d in decays_all
        if _is_alertable(d.file, file_filter)
        and _passes_importance(d.file, importance_map, importance_threshold)
    ]
    decay_services = decay_engine.for_services(commits, ownership, service_of=service_of)

    if services:
        svc_table = Table(title="Service risk (bus factor)")
        svc_table.add_column("Service")
        svc_table.add_column("Files", justify="right")
        svc_table.add_column("Bus factor", justify="right")
        svc_table.add_column("Risk")
        svc_table.add_column("Top owner")
        for s in services[:10]:
            risk_color = {
                "critical": "red",
                "high": "yellow",
                "medium": "cyan",
                "healthy": "green",
            }[s.risk_level]
            top_owner = (
                f"{ownership.label_for(s.top_owners[0][0])} ({s.top_owners[0][1]:.0%})"
                if s.top_owners
                else "-"
            )
            svc_table.add_row(
                s.service,
                str(s.file_count),
                str(s.bus_factor),
                f"[{risk_color}]{s.risk_level}[/{risk_color}]",
                top_owner,
            )
        console.print(svc_table)

    if critical_files:
        file_table = Table(title=f"Critical files ({len(critical_files)} total — top 10)")
        file_table.add_column("File")
        file_table.add_column("Owner")
        file_table.add_column("Coverage", justify="right")
        for f in critical_files[:10]:
            owner_email, owner_cov = f.top_owners[0]
            file_table.add_row(
                f.file, ownership.label_for(owner_email), f"[red]{owner_cov:.0%}[/red]"
            )
        console.print(file_table)

    top_rubber: tuple = ()
    low_div: tuple = ()
    if review_graph is not None:
        rubber = [
            s for s in review_graph.file_stats.values()
            if s.rubber_stamp_ratio >= 0.5
            and s.total_reviews >= 2
            and _is_alertable(s.file, file_filter)
            and _passes_importance(s.file, importance_map, importance_threshold)
        ]
        rubber.sort(key=lambda s: (-s.rubber_stamp_ratio, -s.total_reviews))
        top_rubber = tuple(rubber[:10])

        diversity = [
            s for s in review_graph.file_stats.values()
            if s.total_reviews >= 3
            and _is_alertable(s.file, file_filter)
            and _passes_importance(s.file, importance_map, importance_threshold)
        ]
        diversity.sort(key=lambda s: s.diversity_hhi)
        low_div = tuple(diversity[:10])

    if diff_summary is not None:
        mix_table = Table(title="PR activity mix")
        mix_table.add_column("Category")
        mix_table.add_column("Count", justify="right")
        mix_table.add_column("Share", justify="right")
        for cat, count in sorted(
            diff_summary.counts.items(), key=lambda kv: kv[1], reverse=True
        ):
            if count == 0:
                continue
            share = diff_summary.ratios[cat]
            mix_table.add_row(cat.value, str(count), f"{share:.0%}")
        console.print(mix_table)

    correction_report = CorrectionLoadEngine().compute(commits)
    ai_readiness = AIReadinessEngine().detect(files)

    # Top author by aggregated ownership coverage — used by the profile
    # detector to tell "founder-led" from "team-based".
    _author_total: dict[str, float] = {}
    for s in ownership.scores:
        _author_total[s.author_email] = _author_total.get(s.author_email, 0.0) + s.coverage
    _total_coverage = sum(_author_total.values()) or 1.0
    _top_author_coverage = (
        max(_author_total.values()) / _total_coverage if _author_total else None
    )
    repo_profile = detect_profile(
        commit_count=len(commits),
        author_count=len(authors),
        files=files,
        services_count=len(services),
        top_author_coverage=_top_author_coverage,
    )

    resilience = ResilienceScoreEngine().compute(
        services,
        decays,
        review_stats=review_graph.file_stats if review_graph is not None else None,
    )
    band_color = {
        "Strong": "green",
        "Moderate": "cyan",
        "Fragile": "yellow",
        "Critical": "red",
    }[resilience.band]
    sub_parts = []
    for label, val in (
        ("Ownership", resilience.ownership),
        ("Decay", resilience.decay),
        ("Review", resilience.review),
    ):
        sub_parts.append(f"{label}: {val if val is not None else '—'}")
    panel_body = (
        f"[bold {band_color}]{resilience.overall}/100[/bold {band_color}]  "
        f"[{band_color}]{resilience.band}[/{band_color}]\n"
        f"{'  ·  '.join(sub_parts)}\n"
        f"[dim]{resilience.summary}[/dim]"
    )
    console.print(
        Panel(panel_body, title="Engineering Resilience Score", border_style=band_color)
    )

    if codeowners_report is not None and codeowners_report.findings:
        individual = (
            len(codeowners_report.aligned)
            + len(codeowners_report.mismatches)
            + len(codeowners_report.stale)
            + len(codeowners_report.orphans)
        )
        team_only = len(codeowners_report.team_only)
        if individual == 0 and team_only > 0:
            console.print(
                f"[yellow]CODEOWNERS exists but every rule is team-only "
                f"(@org/team); {team_only} files matched team rules. "
                f"Add at least one @username for per-file validation.[/yellow]"
            )
        else:
            cats = {
                "aligned": len(codeowners_report.aligned),
                "mismatch": len(codeowners_report.mismatches),
                "stale": len(codeowners_report.stale),
                "orphan": len(codeowners_report.orphans),
                "team_only": team_only,
            }
            co_table = Table(title="CODEOWNERS validation")
            co_table.add_column("Category")
            co_table.add_column("Files", justify="right")
            cat_color = {
                "aligned": "green", "mismatch": "red", "stale": "yellow",
                "orphan": "yellow", "team_only": "cyan",
            }
            for cat, count in cats.items():
                color = cat_color[cat]
                co_table.add_row(f"[{color}]{cat}[/{color}]", str(count))
            console.print(co_table)

    if since_days < 90:
        console.print(
            "[dim]Trend wants ≥90 days of history; "
            f"using available {since_days}-day window.[/dim]"
        )
    trend = TrendEngine().compute(commits)
    if trend.snapshots:
        trend_table = Table(title="Resilience trend (overall · ownership · decay)")
        trend_table.add_column("As of")
        trend_table.add_column("Overall", justify="right")
        trend_table.add_column("Ownership", justify="right")
        trend_table.add_column("Decay", justify="right")
        trend_table.add_column("Band")
        for snap in trend.snapshots:
            label = "now" if snap.days_ago == 0 else f"{snap.days_ago}d ago"
            bcolor = {
                "Strong": "green", "Moderate": "cyan",
                "Fragile": "yellow", "Critical": "red",
            }[snap.score.band]
            trend_table.add_row(
                label,
                str(snap.score.overall),
                str(snap.score.ownership) if snap.score.ownership is not None else "—",
                str(snap.score.decay) if snap.score.decay is not None else "—",
                f"[{bcolor}]{snap.score.band}[/{bcolor}]",
            )
        console.print(trend_table)
        if trend.delta_overall is not None:
            arrow = "▲" if trend.delta_overall > 0 else ("▼" if trend.delta_overall < 0 else "—")
            dcolor = "green" if trend.delta_overall > 0 else ("red" if trend.delta_overall < 0 else "dim")
            console.print(
                f"[{dcolor}]{arrow} {trend.delta_overall:+d} overall vs oldest snapshot[/{dcolor}]"
            )

    departure_scenarios: tuple[DepartureReport, ...] = ()
    sim = DepartureSimulation()

    multi_person_scenario: DepartureReport | None = None
    if simulate_departures and ownership.scores:
        multi_emails = [
            e.strip() for e in simulate_departures.split(",") if e.strip()
        ]
        if multi_emails:
            multi_person_scenario = sim.simulate(
                ownership, multi_emails, service_of=service_of
            )
            console.print(
                f"Simulating multi-person departure: "
                f"[bold]{', '.join(multi_emails)}[/bold]"
            )

    if simulate_top_departures > 0 and ownership.scores:
        by_author_cov: dict[str, float] = {}
        for s in ownership.scores:
            by_author_cov[s.author_email] = (
                by_author_cov.get(s.author_email, 0.0) + s.coverage
            )
        top_emails = [
            email for email, _ in sorted(by_author_cov.items(), key=lambda kv: -kv[1])
        ][:simulate_top_departures]
        single_scenarios = tuple(
            sim.simulate(ownership, [email], service_of=service_of)
            for email in top_emails
        )
        console.print(
            f"Simulating departure of top {len(single_scenarios)} "
            f"contributor{'s' if len(single_scenarios) != 1 else ''} "
            f"by aggregate coverage…"
        )
        departure_scenarios = single_scenarios

    # Multi-person scenario goes first (user-requested, more prominent).
    if multi_person_scenario is not None:
        departure_scenarios = (multi_person_scenario,) + departure_scenarios

    ctx = ReportContext(
        repo_path=str(path.resolve()),
        generated_at=datetime.now(UTC),
        since_days=since_days,
        blindspot_version=__version__,
        commit_count=len(commits),
        author_count=len(authors),
        file_count=len(files),
        additions=total_additions,
        deletions=total_deletions,
        services=tuple(services),
        critical_files=tuple(critical_files[:20]),
        decay_top=tuple(decays[:20]),
        decay_services=tuple(decay_services),
        names=dict(ownership.names),
        reviews_enabled=reviews_enabled,
        detected_remote=detected_remote,
        pr_count=pr_count,
        pr_truncated=pr_truncated,
        top_rubber_stamps=top_rubber,
        low_diversity_files=low_div,
        diff_summary=diff_summary,
        recommendations=(),
        resilience=resilience,
        trend=trend,
        codeowners=codeowners_report,
        top_central_files=top_central,
        module_graph=module_graph,
        top_central_models=top_central_models,
        departure_scenarios=departure_scenarios,
        correction_load_authors=correction_report.authors,
        correction_load_files=correction_report.files,
        ai_readiness=ai_readiness,
        repo_profile=repo_profile,
    )

    # Per-service: up to 3 highest-importance code files (fallback: highest-
    # coverage critical file). Lets the diversification recommendation turn
    # a "1589 files" number into a concrete starter list.
    _service_buckets: dict[str, list[str]] = {}
    for cf in critical_files:
        svc = service_of(cf.file)
        _service_buckets.setdefault(svc, []).append(cf.file)
    service_top_files: dict[str, tuple[str, ...]] = {}
    for svc, files in _service_buckets.items():
        ranked = sorted(
            files,
            key=lambda f: -importance_map.get(f, 0.0),
        )
        service_top_files[svc] = tuple(ranked[:3])

    rec_ctx = RecommendationContext(
        services=tuple(services),
        critical_files=tuple(critical_files),
        decays=tuple(decays),
        review_stats=(review_graph.file_stats if review_graph is not None else {}),
        ownership_names=dict(ownership.names),
        codeowners_report=codeowners_report,
        importance_map=importance_map,
        correction_load_authors=correction_report.authors,
        correction_load_files=correction_report.files,
        ai_readiness=ai_readiness,
        service_top_files=service_top_files,
    )
    recommendations = tuple(
        RecommendationEngine(importance_threshold=importance_threshold).recommend(rec_ctx)
    )
    if recommendations:
        rec_table = Table(title=f"Recommended actions ({len(recommendations)})")
        rec_table.add_column("Priority")
        rec_table.add_column("Category")
        rec_table.add_column("Title")
        rec_table.add_column("Target")
        prio_color = {"High": "red", "Medium": "yellow", "Low": "cyan"}
        for a in recommendations[:10]:
            color = prio_color[a.priority.value]
            rec_table.add_row(
                f"[{color}]{a.priority.value}[/{color}]",
                a.category.value,
                a.title,
                a.target,
            )
        console.print(rec_table)
    ctx = replace(ctx, recommendations=recommendations)

    # Narrative — always-on. Cloud LLM if api_key configured, else
    # rule-based fallback (deterministic, in-process, no network).
    if narrative_lang not in ("en", "tr"):
        console.print(
            f"[yellow]Unknown --narrative-lang '{narrative_lang}', falling back to 'en'.[/yellow]"
        )
        narrative_lang = "en"
    try:
        n_cfg = load_narrative_config(
            repo_path=path,
            cli_api_key=api_key or None,
            cli_model=model or None,
            cli_provider=provider or None,
        )
        if n_cfg.api_key:
            console.print(
                f"Generating narrative ({narrative_lang}) via "
                f"[bold]{n_cfg.provider}/{n_cfg.model or 'default'}[/bold]…"
            )
        else:
            console.print(
                f"Generating rule-based narrative ({narrative_lang}) "
                f"[dim](in-process, no LLM)[/dim]"
            )
        narrative = generate_narrative(n_cfg, ctx, language=narrative_lang)
        ctx = replace(ctx, narrative=narrative)
        console.print(
            Panel(
                f"[bold]{narrative.headline_action}[/bold]\n\n{narrative.executive_summary}",
                title=f"Executive summary ({narrative.model})",
                border_style="cyan",
            )
        )
    except NarrativeConfigError as e:
        console.print(f"[yellow]Narrative config error:[/yellow] {e}")
    except NarrativeError as e:
        console.print(f"[red]Narrative failed:[/red] {e}")

    html = ReportRenderer().render(ctx)
    output.write_text(html, encoding="utf-8")
    console.print(f"\n[green]✓[/green] Report written to [bold]{output}[/bold]")


@app.command()
def simulate(
    person: list[str] = typer.Option(
        ..., "--person", "-p", help="Person email (repeat for multiple)."
    ),
    path: Path = typer.Argument(Path("."), help="Repository path."),
    since_days: int = typer.Option(180, "--since-days"),
    output: Path = typer.Option(
        Path("blindspot_departure.html"), "--output", "-o",
        help="HTML report output path. Set to an empty string to skip writing a file.",
    ),
    with_narrative: bool = typer.Option(
        False, "--with-narrative",
        help="Add an LLM-generated departure briefing with mitigation steps.",
    ),
    narrative_lang: str = typer.Option(
        "en", "--narrative-lang", help="Language for the LLM narrative: 'en' or 'tr'.",
    ),
    api_key: str = typer.Option("", "--api-key", help="LLM API key."),
    model: str = typer.Option("", "--model", help="LLM model id."),
    provider: str = typer.Option("", "--provider", help="LLM provider."),
) -> None:
    """Simulate the impact of departing people on knowledge coverage."""
    commits = list(GitCollector(path, since_days=since_days).collect())
    ownership = OwnershipEngine().compute(commits)
    report = DepartureSimulation().simulate(ownership, person)

    console.print(
        f"\nSimulating departure of: [bold]{', '.join(report.departing)}[/bold]\n"
    )

    summary = Table(title="Impact summary")
    summary.add_column("Metric")
    summary.add_column("Value", justify="right")
    summary.add_row("Total files in scope", str(report.total_files))
    summary.add_row("Affected (>40% loss)", str(report.affected_files))
    summary.add_row("Orphaned (no strong remaining owner)", str(report.orphaned_files))
    summary.add_row("Average coverage loss", f"{report.avg_coverage_loss:.0%}")
    console.print(summary)

    if report.services:
        svc_table = Table(title="Service impact")
        svc_table.add_column("Service")
        svc_table.add_column("Files", justify="right")
        svc_table.add_column("Orphaned", justify="right")
        svc_table.add_column("Avg loss", justify="right")
        svc_table.add_column("Severity")
        sev_color = {"critical": "red", "high": "yellow", "medium": "cyan", "low": "green"}
        for s in report.services[:15]:
            svc_table.add_row(
                s.service,
                str(s.file_count),
                str(s.orphaned_files),
                f"{s.avg_coverage_loss:.0%}",
                f"[{sev_color[s.severity]}]{s.severity}[/{sev_color[s.severity]}]",
            )
        console.print(svc_table)

    critical = [f for f in report.files if f.severity == "critical"]
    if critical:
        crit_table = Table(title=f"Files becoming orphaned (top 10 of {len(critical)})")
        crit_table.add_column("File")
        crit_table.add_column("Loss", justify="right")
        crit_table.add_column("Remaining top owner")
        crit_table.add_column("Their coverage", justify="right")
        for f in critical[:10]:
            crit_table.add_row(
                f.file,
                f"[red]{f.coverage_loss:.0%}[/red]",
                ownership.label_for(f.remaining_top_owner) if f.remaining_top_owner else "(none)",
                f"{f.remaining_top_coverage:.0%}",
            )
        console.print(crit_table)

    departure_narrative = None
    if with_narrative:
        if narrative_lang not in ("en", "tr"):
            console.print(
                f"[yellow]Unknown --narrative-lang '{narrative_lang}', falling back to 'en'.[/yellow]"
            )
            narrative_lang = "en"
        try:
            cfg = load_narrative_config(
                repo_path=path,
                cli_api_key=api_key or None,
                cli_model=model or None,
                cli_provider=provider or None,
            )
            client = build_client(cfg.provider, cfg.api_key, cfg.model)
            console.print(
                f"\nGenerating departure narrative ({narrative_lang}) "
                f"via [bold]{cfg.provider}/{client.model}[/bold]…"
            )
            departure_narrative = NarrativeEngine(client=client).summarize_departure(
                report, names=dict(ownership.names), language=narrative_lang,
            )
            body = (
                f"[bold]{departure_narrative.headline_action}[/bold]\n\n"
                f"{departure_narrative.executive_summary}"
            )
            if departure_narrative.mitigations:
                body += "\n\n[bold]Mitigations:[/bold]\n"
                body += "\n".join(f"  • {m}" for m in departure_narrative.mitigations)
            console.print(
                Panel(
                    body,
                    title=f"Departure briefing (LLM · {departure_narrative.model})",
                    border_style="cyan",
                )
            )
        except NarrativeConfigError as e:
            console.print(f"[yellow]Narrative skipped:[/yellow] {e}")
        except MissingAPIKey as e:
            console.print(f"[yellow]Narrative skipped:[/yellow] {e}")
        except NarrativeError as e:
            console.print(f"[red]Narrative failed:[/red] {e}")

    if str(output):
        ctx = DepartureContext(
            repo_path=str(path.resolve()),
            generated_at=datetime.now(UTC),
            since_days=since_days,
            blindspot_version=__version__,
            departure=report,
            names=dict(ownership.names),
            narrative=departure_narrative,
            remaining_gaps=compute_remaining_gaps(report),
        )
        html = ReportRenderer().render_departure(ctx)
        output.write_text(html, encoding="utf-8")
        console.print(f"\n[green]✓[/green] Departure report written to [bold]{output}[/bold]")


@app.command()
def version() -> None:
    """Show blindspot version."""
    console.print(f"blindspot [bold]{__version__}[/bold]")
