from dataclasses import replace
from datetime import UTC, datetime
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from blindspot import __version__
from blindspot.actions import RecommendationContext, RecommendationEngine
from blindspot.ai_signal import (
    AIAmplificationDetector,
    AuthorProfile,
    AuthorProfiler,
    QualitySignalEngine,
)
from blindspot.codeowners import (
    CodeOwnersValidator,
    find_codeowners_file,
    parse_codeowners,
)
from blindspot.narrative import (
    NarrativeConfigError,
    NarrativeEngine,
    load_narrative_config,
)
from blindspot.narrative.client import MissingAPIKey, NarrativeError, build_client
from blindspot.collector import GitCollector
from blindspot.collector.filters import FileFilter
from blindspot.collector.github import PRCollector, detect_github_remote, make_github_client
from blindspot.dependency_graph import (
    DependencyGraphBuilder,
    ImportanceEngine,
    ModuleGraph,
    aggregate_modules,
    top_n as central_top_n,
)
from blindspot.dependency_graph.llm_fallback import LLMImportExtractor
from blindspot.diff_analysis import DiffChurnSummary, classify_file, summarise
from blindspot.ownership import OwnershipEngine
from blindspot.report import ReportContext, ReportRenderer
from blindspot.resilience import ResilienceScoreEngine
from blindspot.review_graph import ReviewGraph, ReviewGraphBuilder
from blindspot.risk_models import (
    BusFactorEngine,
    DepartureSimulation,
    KnowledgeDecayEngine,
)
from blindspot.trend import TrendEngine

app = typer.Typer(
    name="blindspot",
    help="Knowledge Factor — the bus factor for the AI era.",
    no_args_is_help=True,
)
console = Console()


def _is_alertable(path: str, file_filter: FileFilter) -> bool:
    """Same gate the recommendation rules use, for display tables.

    A path is alertable iff it's product code (not test/docs/chore) AND
    not classified as generated by the file filter. Keeps display
    consistent with recommendation output.
    """
    if file_filter.is_generated(path):
        return False
    return classify_file(path) == "code"


def _passes_importance(
    path: str, importance_map: dict[str, float], threshold: float
) -> bool:
    """Mirror of RecommendationEngine._passes_importance for display tables.

    Empty map → no filtering (graph disabled / no imports). Otherwise keep
    only files whose PageRank importance meets the threshold. Files absent
    from the graph (e.g. unsupported language) are treated as below
    threshold and dropped from display, matching recommendation behavior.
    """
    if not importance_map:
        return True
    return importance_map.get(path, 0.0) >= threshold


@app.command()
def scan(
    path: Path = typer.Argument(Path("."), help="Repository path to scan."),
    output: Path = typer.Option(
        Path("blindspot_report.html"), "--output", "-o", help="HTML report output path."
    ),
    since_days: int = typer.Option(180, "--since-days", help="Analysis window in days."),
    include_merges: bool = typer.Option(False, "--include-merges"),
    with_reviews: bool = typer.Option(
        False,
        "--with-reviews",
        help="Fetch PR/review data from GitHub. Anonymous API, rate limited to 60/hr.",
    ),
    max_prs: int = typer.Option(
        50, "--max-prs", help="Maximum PRs to fetch when --with-reviews is set."
    ),
    experimental_ai_signal: bool = typer.Option(
        False,
        "--experimental-ai-signal",
        help="EXPERIMENTAL: classify authors by AI amplification + quality signals.",
    ),
    with_trend: bool = typer.Option(
        False,
        "--with-trend",
        help="Compute resilience snapshots at 90/60/30/0 days ago for trend view.",
    ),
    check_codeowners: bool = typer.Option(
        True,
        "--check-codeowners/--no-check-codeowners",
        help="Validate CODEOWNERS file (if present) against actual ownership.",
    ),
    no_dependency_graph: bool = typer.Option(
        False, "--no-dependency-graph",
        help="Skip building the file-dependency graph (faster, but recommendations "
        "won't be filtered by structural importance).",
    ),
    importance_threshold: float = typer.Option(
        0.005, "--importance-threshold",
        help="PageRank threshold below which files are excluded from recommendations.",
    ),
    llm_graph: bool = typer.Option(
        False, "--llm-graph",
        help="Use an LLM to resolve imports for every scanned file and union "
        "the result with the static extractor (subject to --llm-graph-max-calls). "
        "Opt-in only; without this flag no LLM call is made for the graph. "
        "Requires same API config as --with-narrative.",
    ),
    llm_graph_max_calls: int = typer.Option(
        50, "--llm-graph-max-calls",
        help="Cap on LLM calls during --llm-graph (cost guard).",
    ),
    with_narrative: bool = typer.Option(
        False,
        "--with-narrative",
        help="Add an LLM-generated executive summary on top of the report.",
    ),
    narrative_lang: str = typer.Option(
        "en",
        "--narrative-lang",
        help="Language for the LLM narrative: 'en' or 'tr'.",
    ),
    api_key: str = typer.Option(
        "", "--api-key", help="LLM API key (overrides .blindspot.yaml).",
    ),
    model: str = typer.Option(
        "", "--model", help="LLM model id (overrides config).",
    ),
    provider: str = typer.Option(
        "", "--provider", help="LLM provider (default: anthropic).",
    ),
) -> None:
    """Scan a repository and generate a knowledge risk report."""
    collector = GitCollector(path, since_days=since_days, include_merges=include_merges)
    commits = list(collector.collect())

    authors = {c.author_email for c in commits}
    files: set[str] = set()
    total_additions = 0
    total_deletions = 0
    for c in commits:
        for f in c.files:
            files.add(f.path)
            total_additions += f.additions
            total_deletions += f.deletions

    summary = Table(title=f"blindspot scan — {path}")
    summary.add_column("Metric")
    summary.add_column("Value", justify="right")
    summary.add_row("Window (days)", str(since_days))
    summary.add_row("Commits", str(len(commits)))
    summary.add_row("Unique authors", str(len(authors)))
    summary.add_row("Files touched", str(len(files)))
    summary.add_row("Lines added", str(total_additions))
    summary.add_row("Lines deleted", str(total_deletions))
    console.print(summary)

    review_graph: ReviewGraph | None = None
    diff_summary: DiffChurnSummary | None = None
    prs: list = []
    pr_count = 0
    pr_truncated = False
    reviews_enabled = False

    if with_reviews:
        remote = detect_github_remote(path)
        if remote is None:
            console.print(
                "[yellow]No GitHub remote detected — skipping review data.[/yellow]"
            )
        else:
            client, backend = make_github_client(prefer_gh=True)
            limit_msg = {
                "gh": "via [bold]gh[/bold] CLI (5000/hr)",
                "token": "via token (5000/hr)",
                "anonymous": "anonymous (60/hr)",
            }[backend]
            console.print(
                f"Fetching up to {max_prs} PRs for [bold]{remote.slug}[/bold] — {limit_msg}…"
            )
            try:
                pr_collector = PRCollector(
                    client, remote.owner, remote.repo,
                    since_days=since_days, max_prs=max_prs,
                )
                prs, pr_truncated = pr_collector.collect()
            except Exception as e:
                console.print(f"[red]GitHub error:[/red] {e}")
                prs = []
            pr_count = len(prs)
            if pr_count:
                review_graph = ReviewGraphBuilder().build(prs)
                diff_summary = summarise(prs)
                reviews_enabled = True
                msg = f"Fetched {pr_count} PRs"
                if pr_truncated:
                    msg += " (rate-limited — partial data)"
                console.print(f"[green]✓[/green] {msg}")
            else:
                console.print("[yellow]No PR data collected.[/yellow]")

    ownership = OwnershipEngine().compute(commits, review_graph=review_graph)

    codeowners_report = None
    if check_codeowners:
        co_path = find_codeowners_file(path)
        if co_path is not None:
            try:
                codeowners_file = parse_codeowners(co_path)
                codeowners_report = CodeOwnersValidator().validate(
                    codeowners_file, ownership, commits
                )
                console.print(
                    f"CODEOWNERS detected at [bold]{co_path.relative_to(path)}[/bold] "
                    f"({len(codeowners_file.rules)} rules) — validating against ownership…"
                )
            except Exception as e:
                console.print(f"[yellow]Could not parse CODEOWNERS: {e}[/yellow]")

    bus_factor = BusFactorEngine()
    decay_engine = KnowledgeDecayEngine()

    file_filter = FileFilter.from_repo(path)

    importance_map: dict[str, float] = {}
    top_central: tuple = ()
    module_graph: ModuleGraph | None = None
    if not no_dependency_graph:
        try:
            console.print("Building file dependency graph…")
            llm_extractor = None
            if llm_graph:
                try:
                    cfg = load_narrative_config(
                        repo_path=path,
                        cli_api_key=api_key or None,
                        cli_model=model or None,
                        cli_provider=provider or None,
                    )
                    llm_client = build_client(cfg.provider, cfg.api_key, cfg.model)
                    llm_extractor = LLMImportExtractor(
                        client=llm_client,
                        max_calls=llm_graph_max_calls,
                    )
                    console.print(
                        f"  LLM graph enabled "
                        f"([bold]{cfg.provider}/{llm_client.model}[/bold], "
                        f"max {llm_graph_max_calls} calls)"
                    )
                except (NarrativeConfigError, MissingAPIKey) as e:
                    console.print(f"  [yellow]LLM fallback disabled:[/yellow] {e}")
            graph = DependencyGraphBuilder(
                file_filter=file_filter, llm_fallback=llm_extractor,
            ).build(path)
            importance_map = ImportanceEngine().compute(graph)
            module_graph = aggregate_modules(graph)
            if importance_map:
                # Enrich top-N with ownership info from the OwnershipMap.
                ranked = central_top_n(importance_map, graph, n=10)
                enriched = []
                for cf in ranked:
                    fos = ownership.for_file(cf.file)
                    top_email = fos[0].author_email if fos else None
                    top_cov = fos[0].coverage if fos else 0.0
                    enriched.append(
                        replace(cf, top_owner=top_email, top_owner_coverage=top_cov)
                    )
                top_central = tuple(enriched)
                tbl = Table(title=f"Top 10 central files ({graph.file_count} parsed, {graph.edge_count} edges)")
                tbl.add_column("File")
                tbl.add_column("Importance", justify="right")
                tbl.add_column("Dependents", justify="right")
                tbl.add_column("Top owner")
                for cf in top_central:
                    owner_label = (
                        ownership.label_for(cf.top_owner) if cf.top_owner else "—"
                    )
                    tbl.add_row(
                        cf.file,
                        f"{cf.importance * 100:.2f}%",
                        str(cf.in_degree),
                        owner_label,
                    )
                console.print(tbl)
            else:
                console.print(
                    "[dim]Dependency graph built but no importance scores "
                    "(repo may have no import statements in supported languages).[/dim]"
                )
        except Exception as e:
            console.print(f"[yellow]Dependency graph skipped:[/yellow] {e}")

    services = bus_factor.for_services(ownership)
    file_bf = bus_factor.for_files(ownership)
    critical_files = [
        f for f in file_bf
        if f.risk_level == "critical"
        and _is_alertable(f.file, file_filter)
        and _passes_importance(f.file, importance_map, importance_threshold)
    ]
    decays_all = decay_engine.for_files(commits, ownership)
    decays = [
        d for d in decays_all
        if _is_alertable(d.file, file_filter)
        and _passes_importance(d.file, importance_map, importance_threshold)
    ]
    decay_services = decay_engine.for_services(commits, ownership)

    if services:
        svc_table = Table(title="Service risk (bus factor)")
        svc_table.add_column("Service")
        svc_table.add_column("Files", justify="right")
        svc_table.add_column("Bus factor", justify="right")
        svc_table.add_column("Risk")
        svc_table.add_column("Top owner")
        for s in services[:10]:
            risk_color = {
                "critical": "red",
                "high": "yellow",
                "medium": "cyan",
                "healthy": "green",
            }[s.risk_level]
            top_owner = (
                f"{ownership.label_for(s.top_owners[0][0])} ({s.top_owners[0][1]:.0%})"
                if s.top_owners
                else "-"
            )
            svc_table.add_row(
                s.service,
                str(s.file_count),
                str(s.bus_factor),
                f"[{risk_color}]{s.risk_level}[/{risk_color}]",
                top_owner,
            )
        console.print(svc_table)

    if critical_files:
        file_table = Table(title=f"Critical files ({len(critical_files)} total — top 10)")
        file_table.add_column("File")
        file_table.add_column("Owner")
        file_table.add_column("Coverage", justify="right")
        for f in critical_files[:10]:
            owner_email, owner_cov = f.top_owners[0]
            file_table.add_row(
                f.file, ownership.label_for(owner_email), f"[red]{owner_cov:.0%}[/red]"
            )
        console.print(file_table)

    top_rubber: tuple = ()
    low_div: tuple = ()
    if review_graph is not None:
        rubber = [
            s for s in review_graph.file_stats.values()
            if s.rubber_stamp_ratio >= 0.5
            and s.total_reviews >= 2
            and _is_alertable(s.file, file_filter)
            and _passes_importance(s.file, importance_map, importance_threshold)
        ]
        rubber.sort(key=lambda s: (-s.rubber_stamp_ratio, -s.total_reviews))
        top_rubber = tuple(rubber[:10])

        diversity = [
            s for s in review_graph.file_stats.values()
            if s.total_reviews >= 3
            and _is_alertable(s.file, file_filter)
            and _passes_importance(s.file, importance_map, importance_threshold)
        ]
        diversity.sort(key=lambda s: s.diversity_hhi)
        low_div = tuple(diversity[:10])

    if diff_summary is not None:
        mix_table = Table(title="PR activity mix")
        mix_table.add_column("Category")
        mix_table.add_column("Count", justify="right")
        mix_table.add_column("Share", justify="right")
        for cat, count in sorted(
            diff_summary.counts.items(), key=lambda kv: kv[1], reverse=True
        ):
            if count == 0:
                continue
            share = diff_summary.ratios[cat]
            mix_table.add_row(cat.value, str(count), f"{share:.0%}")
        console.print(mix_table)

    author_profiles: tuple[AuthorProfile, ...] = ()
    if experimental_ai_signal:
        console.print(
            "\n[yellow]experimental:[/yellow] computing AI amplification + quality signals "
            "(heuristic — verify before action)…"
        )
        ai_signals = AIAmplificationDetector().detect(commits)
        quality_signals = QualitySignalEngine().assess(
            commits, prs=prs if reviews_enabled else None
        )
        profiles_by_email = AuthorProfiler().profile(commits, ai_signals, quality_signals)
        sort_order = {
            "Fake Velocity": 0,
            "AI Amplified Healthy": 1,
            "Real Growth": 2,
            "Insufficient Data": 3,
            "Bot": 4,
        }
        author_profiles = tuple(
            sorted(
                profiles_by_email.values(),
                key=lambda p: (
                    sort_order.get(p.profile_type.value, 5),
                    -p.ai_signal.score if p.ai_signal else 0,
                ),
            )
        )
        if author_profiles:
            profile_color = {
                "Fake Velocity": "red",
                "AI Amplified Healthy": "yellow",
                "Real Growth": "green",
                "Bot": "cyan",
                "Insufficient Data": "dim",
            }
            ai_table = Table(title="Author signal profiles (experimental)")
            ai_table.add_column("Author")
            ai_table.add_column("Profile")
            ai_table.add_column("AI flag")
            ai_table.add_column("Quality risk", justify="right")
            ai_table.add_column("Signal strength")
            for p in author_profiles:
                color = profile_color[p.profile_type.value]
                ai_flag = p.ai_signal.flag.value if p.ai_signal else "-"
                quality = f"{p.quality_signal.risk_score:.0%}" if p.quality_signal else "-"
                ai_table.add_row(
                    ownership.label_for(p.author_email),
                    f"[{color}]{p.profile_type.value}[/{color}]",
                    ai_flag,
                    quality,
                    p.signal_strength.value,
                )
            console.print(ai_table)

    resilience = ResilienceScoreEngine().compute(
        services,
        decays,
        review_stats=review_graph.file_stats if review_graph is not None else None,
        author_profiles={p.author_email: p for p in author_profiles} if author_profiles else None,
    )
    band_color = {
        "Strong": "green",
        "Moderate": "cyan",
        "Fragile": "yellow",
        "Critical": "red",
    }[resilience.band]
    sub_parts = []
    for label, val in (
        ("Ownership", resilience.ownership),
        ("Decay", resilience.decay),
        ("Review", resilience.review),
        ("Activity", resilience.activity),
    ):
        sub_parts.append(f"{label}: {val if val is not None else '—'}")
    panel_body = (
        f"[bold {band_color}]{resilience.overall}/100[/bold {band_color}]  "
        f"[{band_color}]{resilience.band}[/{band_color}]\n"
        f"{'  ·  '.join(sub_parts)}\n"
        f"[dim]{resilience.summary}[/dim]"
    )
    console.print(
        Panel(panel_body, title="Engineering Resilience Score", border_style=band_color)
    )

    if codeowners_report is not None and codeowners_report.findings:
        individual = (
            len(codeowners_report.aligned)
            + len(codeowners_report.mismatches)
            + len(codeowners_report.stale)
            + len(codeowners_report.orphans)
        )
        team_only = len(codeowners_report.team_only)
        if individual == 0 and team_only > 0:
            console.print(
                f"[yellow]CODEOWNERS exists but every rule is team-only "
                f"(@org/team); {team_only} files matched team rules. "
                f"Add at least one @username for per-file validation.[/yellow]"
            )
        else:
            cats = {
                "aligned": len(codeowners_report.aligned),
                "mismatch": len(codeowners_report.mismatches),
                "stale": len(codeowners_report.stale),
                "orphan": len(codeowners_report.orphans),
                "team_only": team_only,
            }
            co_table = Table(title="CODEOWNERS validation")
            co_table.add_column("Category")
            co_table.add_column("Files", justify="right")
            cat_color = {
                "aligned": "green", "mismatch": "red", "stale": "yellow",
                "orphan": "yellow", "team_only": "cyan",
            }
            for cat, count in cats.items():
                color = cat_color[cat]
                co_table.add_row(f"[{color}]{cat}[/{color}]", str(count))
            console.print(co_table)

    trend = None
    if with_trend:
        if since_days < 90:
            console.print(
                "[yellow]--with-trend wants ≥90 days of history; "
                f"using available {since_days}-day window.[/yellow]"
            )
        trend = TrendEngine().compute(commits)
        if trend.snapshots:
            trend_table = Table(title="Resilience trend (overall · ownership · decay)")
            trend_table.add_column("As of")
            trend_table.add_column("Overall", justify="right")
            trend_table.add_column("Ownership", justify="right")
            trend_table.add_column("Decay", justify="right")
            trend_table.add_column("Band")
            for snap in trend.snapshots:
                label = "now" if snap.days_ago == 0 else f"{snap.days_ago}d ago"
                bcolor = {
                    "Strong": "green", "Moderate": "cyan",
                    "Fragile": "yellow", "Critical": "red",
                }[snap.score.band]
                trend_table.add_row(
                    label,
                    str(snap.score.overall),
                    str(snap.score.ownership) if snap.score.ownership is not None else "—",
                    str(snap.score.decay) if snap.score.decay is not None else "—",
                    f"[{bcolor}]{snap.score.band}[/{bcolor}]",
                )
            console.print(trend_table)
            if trend.delta_overall is not None:
                arrow = "▲" if trend.delta_overall > 0 else ("▼" if trend.delta_overall < 0 else "—")
                dcolor = "green" if trend.delta_overall > 0 else ("red" if trend.delta_overall < 0 else "dim")
                console.print(
                    f"[{dcolor}]{arrow} {trend.delta_overall:+d} overall vs oldest snapshot[/{dcolor}]"
                )

    ctx = ReportContext(
        repo_path=str(path.resolve()),
        generated_at=datetime.now(UTC),
        since_days=since_days,
        blindspot_version=__version__,
        commit_count=len(commits),
        author_count=len(authors),
        file_count=len(files),
        additions=total_additions,
        deletions=total_deletions,
        services=tuple(services),
        critical_files=tuple(critical_files[:20]),
        decay_top=tuple(decays[:20]),
        decay_services=tuple(decay_services),
        names=dict(ownership.names),
        reviews_enabled=reviews_enabled,
        pr_count=pr_count,
        pr_truncated=pr_truncated,
        top_rubber_stamps=top_rubber,
        low_diversity_files=low_div,
        diff_summary=diff_summary,
        ai_signal_enabled=experimental_ai_signal,
        author_profiles=author_profiles,
        recommendations=(),
        resilience=resilience,
        trend=trend,
        codeowners=codeowners_report,
        top_central_files=top_central,
        module_graph=module_graph,
    )

    rec_ctx = RecommendationContext(
        services=tuple(services),
        critical_files=tuple(critical_files),
        decays=tuple(decays),
        review_stats=(review_graph.file_stats if review_graph is not None else {}),
        author_profiles={p.author_email: p for p in author_profiles},
        ownership_names=dict(ownership.names),
        codeowners_report=codeowners_report,
        importance_map=importance_map,
    )
    recommendations = tuple(
        RecommendationEngine(importance_threshold=importance_threshold).recommend(rec_ctx)
    )
    if recommendations:
        rec_table = Table(title=f"Recommended actions ({len(recommendations)})")
        rec_table.add_column("Priority")
        rec_table.add_column("Category")
        rec_table.add_column("Title")
        rec_table.add_column("Target")
        prio_color = {"High": "red", "Medium": "yellow", "Low": "cyan"}
        for a in recommendations[:10]:
            color = prio_color[a.priority.value]
            rec_table.add_row(
                f"[{color}]{a.priority.value}[/{color}]",
                a.category.value,
                a.title,
                a.target,
            )
        console.print(rec_table)
    ctx = replace(ctx, recommendations=recommendations)

    if with_narrative:
        if narrative_lang not in ("en", "tr"):
            console.print(
                f"[yellow]Unknown --narrative-lang '{narrative_lang}', falling back to 'en'.[/yellow]"
            )
            narrative_lang = "en"
        try:
            cfg = load_narrative_config(
                repo_path=path,
                cli_api_key=api_key or None,
                cli_model=model or None,
                cli_provider=provider or None,
            )
            client = build_client(cfg.provider, cfg.api_key, cfg.model)
            console.print(
                f"Generating LLM narrative ({narrative_lang}) "
                f"via [bold]{cfg.provider}/{client.model}[/bold]…"
            )
            narrative = NarrativeEngine(client=client).summarize(
                ctx, language=narrative_lang
            )
            ctx = replace(ctx, narrative=narrative)
            console.print(
                Panel(
                    f"[bold]{narrative.headline_action}[/bold]\n\n{narrative.executive_summary}",
                    title=f"Executive summary (LLM · {narrative.model})",
                    border_style="cyan",
                )
            )
        except NarrativeConfigError as e:
            console.print(f"[yellow]Narrative skipped:[/yellow] {e}")
        except MissingAPIKey as e:
            console.print(f"[yellow]Narrative skipped:[/yellow] {e}")
        except NarrativeError as e:
            console.print(f"[red]Narrative failed:[/red] {e}")

    html = ReportRenderer().render(ctx)
    output.write_text(html, encoding="utf-8")
    console.print(f"\n[green]✓[/green] Report written to [bold]{output}[/bold]")


@app.command()
def simulate(
    person: list[str] = typer.Option(
        ..., "--person", "-p", help="Person email (repeat for multiple)."
    ),
    path: Path = typer.Argument(Path("."), help="Repository path."),
    since_days: int = typer.Option(180, "--since-days"),
    with_narrative: bool = typer.Option(
        False, "--with-narrative",
        help="Add an LLM-generated departure briefing with mitigation steps.",
    ),
    narrative_lang: str = typer.Option(
        "en", "--narrative-lang", help="Language for the LLM narrative: 'en' or 'tr'.",
    ),
    api_key: str = typer.Option("", "--api-key", help="LLM API key."),
    model: str = typer.Option("", "--model", help="LLM model id."),
    provider: str = typer.Option("", "--provider", help="LLM provider."),
) -> None:
    """Simulate the impact of departing people on knowledge coverage."""
    commits = list(GitCollector(path, since_days=since_days).collect())
    ownership = OwnershipEngine().compute(commits)
    report = DepartureSimulation().simulate(ownership, person)

    console.print(
        f"\nSimulating departure of: [bold]{', '.join(report.departing)}[/bold]\n"
    )

    summary = Table(title="Impact summary")
    summary.add_column("Metric")
    summary.add_column("Value", justify="right")
    summary.add_row("Total files in scope", str(report.total_files))
    summary.add_row("Affected (>40% loss)", str(report.affected_files))
    summary.add_row("Orphaned (no strong remaining owner)", str(report.orphaned_files))
    summary.add_row("Average coverage loss", f"{report.avg_coverage_loss:.0%}")
    console.print(summary)

    if report.services:
        svc_table = Table(title="Service impact")
        svc_table.add_column("Service")
        svc_table.add_column("Files", justify="right")
        svc_table.add_column("Orphaned", justify="right")
        svc_table.add_column("Avg loss", justify="right")
        svc_table.add_column("Severity")
        sev_color = {"critical": "red", "high": "yellow", "medium": "cyan", "low": "green"}
        for s in report.services[:15]:
            svc_table.add_row(
                s.service,
                str(s.file_count),
                str(s.orphaned_files),
                f"{s.avg_coverage_loss:.0%}",
                f"[{sev_color[s.severity]}]{s.severity}[/{sev_color[s.severity]}]",
            )
        console.print(svc_table)

    critical = [f for f in report.files if f.severity == "critical"]
    if critical:
        crit_table = Table(title=f"Files becoming orphaned (top 10 of {len(critical)})")
        crit_table.add_column("File")
        crit_table.add_column("Loss", justify="right")
        crit_table.add_column("Remaining top owner")
        crit_table.add_column("Their coverage", justify="right")
        for f in critical[:10]:
            crit_table.add_row(
                f.file,
                f"[red]{f.coverage_loss:.0%}[/red]",
                ownership.label_for(f.remaining_top_owner) if f.remaining_top_owner else "(none)",
                f"{f.remaining_top_coverage:.0%}",
            )
        console.print(crit_table)

    if with_narrative:
        if narrative_lang not in ("en", "tr"):
            console.print(
                f"[yellow]Unknown --narrative-lang '{narrative_lang}', falling back to 'en'.[/yellow]"
            )
            narrative_lang = "en"
        try:
            cfg = load_narrative_config(
                repo_path=path,
                cli_api_key=api_key or None,
                cli_model=model or None,
                cli_provider=provider or None,
            )
            client = build_client(cfg.provider, cfg.api_key, cfg.model)
            console.print(
                f"\nGenerating departure narrative ({narrative_lang}) "
                f"via [bold]{cfg.provider}/{client.model}[/bold]…"
            )
            narrative = NarrativeEngine(client=client).summarize_departure(
                report, names=dict(ownership.names), language=narrative_lang,
            )
            body = f"[bold]{narrative.headline_action}[/bold]\n\n{narrative.executive_summary}"
            if narrative.mitigations:
                body += "\n\n[bold]Mitigations:[/bold]\n"
                body += "\n".join(f"  • {m}" for m in narrative.mitigations)
            console.print(
                Panel(
                    body,
                    title=f"Departure briefing (LLM · {narrative.model})",
                    border_style="cyan",
                )
            )
        except NarrativeConfigError as e:
            console.print(f"[yellow]Narrative skipped:[/yellow] {e}")
        except MissingAPIKey as e:
            console.print(f"[yellow]Narrative skipped:[/yellow] {e}")
        except NarrativeError as e:
            console.print(f"[red]Narrative failed:[/red] {e}")


@app.command()
def version() -> None:
    """Show blindspot version."""
    console.print(f"blindspot [bold]{__version__}[/bold]")
